<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VoiceTranscribe.Core\VoiceTranscribe.Core.csproj" />
    <PackageReference Include="System.CommandLine" Version="2.*" />
    <PackageReference Include="NAudio" Version="2.*" />
  </ItemGroup>
</Project>
